import type {
  Booking,
  Post,
  Review,
  Testimonial,
  User,
  Vehicle,
} from "@/types";

// ─── Mock data — swap for Supabase queries later ─────────────────────────────
// Image URLs use Unsplash; replace with Cloudinary (res.cloudinary.com) later.

const img = (id: string) =>
  `https://images.unsplash.com/${id}?f_auto&q_auto&w_1600`;

export const OWNERS: User[] = [
  {
    id: "own-1",
    role: "owner",
    name: "Jean-Bosco Mugisha",
    email: "owner@lora.rw",
    phone: "+250 788 111 222",
    kycStatus: "verified",
    businessName: "Mugisha Motors",
    payoutMethod: "momo",
    payoutDetails: "+250 788 111 222",
    createdAt: "2024-02-10T08:00:00Z",
  },
  {
    id: "own-2",
    role: "owner",
    name: "Aline Uwase",
    email: "aline@lorarentals.rw",
    phone: "+250 788 333 444",
    kycStatus: "verified",
    businessName: "Uwase Fleet",
    payoutMethod: "bank",
    payoutDetails: "BK ****4521",
    createdAt: "2024-03-02T08:00:00Z",
  },
  {
    id: "own-3",
    role: "owner",
    name: "Eric Nshimiyimana",
    email: "eric@lorarentals.rw",
    phone: "+250 788 555 666",
    kycStatus: "verified",
    businessName: "Kigali 4x4 Co.",
    payoutMethod: "momo",
    payoutDetails: "+250 788 555 666",
    createdAt: "2024-04-18T08:00:00Z",
  },
  {
    id: "own-4",
    role: "owner",
    name: "Claudine Mukamana",
    email: "claudine@lorarentals.rw",
    phone: "+250 788 777 888",
    kycStatus: "pending",
    businessName: "CM Rentals",
    createdAt: "2025-11-20T08:00:00Z",
  },
  {
    id: "own-5",
    role: "owner",
    name: "Patrick Habimana",
    email: "patrick@lorarentals.rw",
    phone: "+250 788 999 000",
    kycStatus: "verified",
    businessName: "Habimana Auto",
    payoutMethod: "momo",
    payoutDetails: "+250 788 999 000",
    createdAt: "2024-06-05T08:00:00Z",
  },
];

export const CUSTOMERS: User[] = [
  {
    id: "cus-1",
    role: "customer",
    name: "Diane Ingabire",
    email: "customer@lora.rw",
    phone: "+250 788 100 200",
    kycStatus: "verified",
    createdAt: "2025-01-15T08:00:00Z",
  },
  {
    id: "cus-2",
    role: "customer",
    name: "Samuel Nkurunziza",
    email: "samuel@example.rw",
    phone: "+250 788 300 400",
    kycStatus: "verified",
    createdAt: "2025-03-22T08:00:00Z",
  },
  {
    id: "cus-3",
    role: "customer",
    name: "Grace Umutoni",
    email: "grace@example.rw",
    phone: "+250 788 500 600",
    kycStatus: "pending",
    createdAt: "2025-08-10T08:00:00Z",
  },
];

export const ADMIN: User = {
  id: "adm-1",
  role: "admin",
  name: "LORA Admin",
  email: "admin@lora.rw",
  phone: "+250 788 000 000",
  kycStatus: "verified",
  createdAt: "2024-01-01T08:00:00Z",
};

export const ALL_USERS: User[] = [...CUSTOMERS, ...OWNERS, ADMIN];

export const VEHICLES: Vehicle[] = [
  {
    id: "veh-1",
    ownerId: "own-1",
    make: "Toyota",
    model: "Land Cruiser V8",
    year: 2022,
    plate: "RAE 412 B",
    type: "4x4",
    transmission: "automatic",
    fuel: "diesel",
    seats: 7,
    pricePerDay: 150000,
    location: "Kigali — Gasabo",
    coordinates: { lat: -1.9355, lng: 30.0975 },
    images: [
      img("photo-1568844293986-8d0400bd4745"),
      img("photo-1533473359331-0135ef1b58bf"),
      img("photo-1519641471654-76ce0107ad1b"),
    ],
    features: ["4WD", "Air Conditioning", "GPS Navigation", "Leather Seats", "Roof Rack", "Reverse Camera"],
    description:
      "Flagship Land Cruiser built for Rwanda's hills and national parks. Ideal for Akagera safaris and Volcanoes gorilla treks.",
    status: "available",
    verified: true,
    rating: 4.9,
    reviewCount: 87,
    tripsCompleted: 132,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-03-01T08:00:00Z",
  },
  {
    id: "veh-2",
    ownerId: "own-2",
    make: "Mercedes-Benz",
    model: "E-Class",
    year: 2021,
    plate: "RAF 208 C",
    type: "luxury",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    pricePerDay: 120000,
    location: "Kigali — Nyarugenge",
    coordinates: { lat: -1.9501, lng: 30.0588 },
    images: [
      img("photo-1618843479313-40f8afb4b4d8"),
      img("photo-1617531653332-bd46c24f2068"),
    ],
    features: ["Leather Seats", "Sunroof", "Apple CarPlay", "Cruise Control", "Air Conditioning"],
    description:
      "Executive E-Class for business travel and special occasions. Chauffeur option available.",
    status: "available",
    verified: true,
    rating: 4.8,
    reviewCount: 54,
    tripsCompleted: 78,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-04-10T08:00:00Z",
  },
  {
    id: "veh-3",
    ownerId: "own-1",
    make: "Toyota",
    model: "RAV4",
    year: 2023,
    plate: "RAG 915 D",
    type: "suv",
    transmission: "automatic",
    fuel: "hybrid",
    seats: 5,
    pricePerDay: 75000,
    location: "Kigali — Kicukiro",
    coordinates: { lat: -1.9706, lng: 30.1044 },
    images: [
      img("photo-1621007947382-bb3c3994e3fb"),
      img("photo-1580273916550-e323be2ae537"),
    ],
    features: ["Air Conditioning", "Bluetooth", "Reverse Camera", "Apple CarPlay", "Cruise Control"],
    description:
      "Fuel-sipping hybrid RAV4 — perfect city runabout that still handles upcountry roads with ease.",
    status: "available",
    verified: true,
    rating: 4.7,
    reviewCount: 112,
    tripsCompleted: 201,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-05-15T08:00:00Z",
  },
  {
    id: "veh-4",
    ownerId: "own-3",
    make: "Toyota",
    model: "Hilux Double Cab",
    year: 2022,
    plate: "RAE 677 E",
    type: "pickup",
    transmission: "manual",
    fuel: "diesel",
    seats: 5,
    pricePerDay: 90000,
    location: "Musanze",
    coordinates: { lat: -1.4998, lng: 29.6350 },
    images: [
      img("photo-1559416523-140ddc3d238c"),
      img("photo-1535732820275-9ffd998cac22"),
    ],
    features: ["4WD", "Roof Rack", "Air Conditioning", "Bluetooth", "Dash Cam"],
    description:
      "Workhorse Hilux based in Musanze — the go-to for gorilla trekking crews and construction sites.",
    status: "available",
    verified: true,
    rating: 4.6,
    reviewCount: 63,
    tripsCompleted: 95,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-06-20T08:00:00Z",
  },
  {
    id: "veh-5",
    ownerId: "own-2",
    make: "Toyota",
    model: "Corolla",
    year: 2021,
    plate: "RAF 331 F",
    type: "sedan",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    pricePerDay: 45000,
    location: "Kigali — Gasabo",
    coordinates: { lat: -1.9297, lng: 30.1127 },
    images: [
      img("photo-1623869675781-80aa31012a5a"),
      img("photo-1590362891991-f776e747a588"),
    ],
    features: ["Air Conditioning", "Bluetooth", "USB Charging", "Reverse Camera"],
    description:
      "Reliable, economical Corolla — the smart choice for city errands and airport runs.",
    status: "available",
    verified: true,
    rating: 4.5,
    reviewCount: 148,
    tripsCompleted: 264,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-02-25T08:00:00Z",
  },
  {
    id: "veh-6",
    ownerId: "own-3",
    make: "Land Rover",
    model: "Defender 110",
    year: 2023,
    plate: "RAG 044 G",
    type: "4x4",
    transmission: "automatic",
    fuel: "diesel",
    seats: 7,
    pricePerDay: 180000,
    location: "Rubavu",
    coordinates: { lat: -1.6794, lng: 29.2668 },
    images: [
      img("photo-1606016159991-dfe4f2746ad5"),
      img("photo-1568605117036-5fe5e7bab0b7"),
    ],
    features: ["4WD", "Leather Seats", "GPS Navigation", "Roof Rack", "360 Camera", "Air Conditioning"],
    description:
      "Iconic Defender stationed in Rubavu — Lake Kivu weekends and Congo-Nile trail adventures.",
    status: "available",
    verified: true,
    rating: 4.9,
    reviewCount: 41,
    tripsCompleted: 58,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-08-01T08:00:00Z",
  },
  {
    id: "veh-7",
    ownerId: "own-5",
    make: "Toyota",
    model: "Hiace",
    year: 2020,
    plate: "RAD 552 H",
    type: "minivan",
    transmission: "manual",
    fuel: "diesel",
    seats: 14,
    pricePerDay: 85000,
    location: "Huye",
    coordinates: { lat: -2.5967, lng: 29.7389 },
    images: [
      img("photo-1570125909232-eb263c188f7e"),
      img("photo-1544620347-c4fd4a3d5957"),
    ],
    features: ["Air Conditioning", "USB Charging", "Bluetooth"],
    description:
      "14-seat Hiace for group travel, weddings, and corporate shuttles across the Southern Province.",
    status: "available",
    verified: true,
    rating: 4.4,
    reviewCount: 76,
    tripsCompleted: 143,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-03-18T08:00:00Z",
  },
  {
    id: "veh-8",
    ownerId: "own-5",
    make: "Kia",
    model: "Sorento",
    year: 2022,
    plate: "RAF 890 J",
    type: "suv",
    transmission: "automatic",
    fuel: "diesel",
    seats: 7,
    pricePerDay: 80000,
    location: "Kigali — Kicukiro",
    coordinates: { lat: -1.9660, lng: 30.0860 },
    images: [
      img("photo-1619405399517-d7fce0f13302"),
      img("photo-1549317661-bd32c8ce0db2"),
    ],
    features: ["7 Seats", "Air Conditioning", "Apple CarPlay", "Reverse Camera", "Cruise Control"],
    description:
      "Spacious 7-seat Sorento — family trips to Akagera or cross-border runs made comfortable.",
    status: "available",
    verified: true,
    rating: 4.6,
    reviewCount: 59,
    tripsCompleted: 88,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-07-12T08:00:00Z",
  },
  {
    id: "veh-9",
    ownerId: "own-1",
    make: "BMW",
    model: "X5",
    year: 2022,
    plate: "RAE 123 K",
    type: "luxury",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    pricePerDay: 140000,
    location: "Kigali — Gasabo",
    coordinates: { lat: -1.9441, lng: 30.0619 },
    images: [
      img("photo-1555215695-3004980ad54e"),
      img("photo-1556189250-72ba954cfc2b"),
    ],
    features: ["Leather Seats", "Sunroof", "Apple CarPlay", "360 Camera", "Cruise Control", "Air Conditioning"],
    description:
      "Commanding X5 for executives and VIP transfers. Airport delivery available on request.",
    status: "available",
    verified: true,
    rating: 4.8,
    reviewCount: 37,
    tripsCompleted: 49,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-09-05T08:00:00Z",
  },
  {
    id: "veh-10",
    ownerId: "own-4",
    make: "Suzuki",
    model: "Jimny",
    year: 2023,
    plate: "RAG 456 L",
    type: "4x4",
    transmission: "manual",
    fuel: "petrol",
    seats: 4,
    pricePerDay: 60000,
    location: "Nyagatare",
    coordinates: { lat: -1.2968, lng: 30.3269 },
    images: [
      img("photo-1533106418989-88406c7cc8ca"),
      img("photo-1502877338535-766e1452684a"),
    ],
    features: ["4WD", "Air Conditioning", "Bluetooth", "Roof Rack"],
    description:
      "Pocket-sized 4x4 that punches far above its weight — Akagera game drives on a budget.",
    status: "pending_approval",
    verified: false,
    rating: 0,
    reviewCount: 0,
    tripsCompleted: 0,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "veh-11",
    ownerId: "own-3",
    make: "Toyota",
    model: "Prado TX",
    year: 2021,
    plate: "RAE 789 M",
    type: "suv",
    transmission: "automatic",
    fuel: "diesel",
    seats: 7,
    pricePerDay: 110000,
    location: "Musanze",
    coordinates: { lat: -1.5033, lng: 29.6280 },
    images: [
      img("photo-1594502184342-2e12f877aa73"),
      img("photo-1511919884226-fd3cad34687c"),
    ],
    features: ["4WD", "7 Seats", "Air Conditioning", "GPS Navigation", "Roof Rack"],
    description:
      "The classic Rwandan upcountry SUV — Prado comfort with genuine off-road capability.",
    status: "available",
    verified: true,
    rating: 4.7,
    reviewCount: 92,
    tripsCompleted: 156,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-05-30T08:00:00Z",
  },
  {
    id: "veh-12",
    ownerId: "own-2",
    make: "Hyundai",
    model: "Tucson",
    year: 2022,
    plate: "RAF 234 N",
    type: "suv",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    pricePerDay: 65000,
    location: "Kigali — Nyarugenge",
    coordinates: { lat: -1.9536, lng: 30.0605 },
    images: [
      img("photo-1632245889029-e406faaa34cd"),
      img("photo-1605559424843-9e4c228bf1c2"),
    ],
    features: ["Air Conditioning", "Apple CarPlay", "Reverse Camera", "Bluetooth", "Cruise Control"],
    description:
      "Modern Tucson with a full tech suite — effortless city driving and weekend escapes.",
    status: "available",
    verified: true,
    rating: 4.5,
    reviewCount: 44,
    tripsCompleted: 71,
    paymentMethods: ["cash", "momo", "card"],
    airportApproved: false,
    createdAt: "2024-10-14T08:00:00Z",
  },
];

export const BOOKINGS: Booking[] = [
  {
    id: "bk-1001",
    customerId: "cus-1",
    vehicleId: "veh-1",
    ownerId: "own-1",
    startDate: "2026-09-18",
    endDate: "2026-09-21",
    pickupLocation: "Kigali — Gasabo",
    returnLocation: "Kigali — Gasabo",
    extras: ["gps"],
    totalPrice: 459000,
    bookingFee: 0,
    status: "confirmed",
    paymentMethod: "momo",
    paymentPoint: "pickup",
    paymentConfirmed: false,
    qrCode: "LRA-BK1001-DIANE",
    driverName: "Diane Ingabire",
    driverLicense: "DL-2020-88412",
    createdAt: "2026-09-08T10:30:00Z",
  },
  {
    id: "bk-1002",
    customerId: "cus-1",
    vehicleId: "veh-5",
    ownerId: "own-2",
    startDate: "2026-08-12",
    endDate: "2026-08-14",
    pickupLocation: "Kigali International Airport",
    returnLocation: "Kigali International Airport",
    extras: ["airport-delivery"],
    totalPrice: 90000,
    bookingFee: 0,
    status: "completed",
    paymentMethod: "cash",
    paymentPoint: "pickup",
    paymentConfirmed: true,
    qrCode: "LRA-BK1002-DIANE",
    driverName: "Diane Ingabire",
    driverLicense: "DL-2020-88412",
    createdAt: "2026-08-05T14:10:00Z",
  },
  {
    id: "bk-1003",
    customerId: "cus-2",
    vehicleId: "veh-4",
    ownerId: "own-3",
    startDate: "2026-09-25",
    endDate: "2026-09-28",
    pickupLocation: "Musanze",
    returnLocation: "Musanze",
    extras: ["driver"],
    totalPrice: 345000,
    bookingFee: 0,
    status: "requested",
    paymentMethod: "cash",
    paymentPoint: "office",
    paymentConfirmed: false,
    qrCode: "LRA-BK1003-SAMUEL",
    driverName: "Samuel Nkurunziza",
    driverLicense: "DL-2019-55231",
    createdAt: "2026-09-10T09:00:00Z",
  },
  {
    id: "bk-1004",
    customerId: "cus-3",
    vehicleId: "veh-3",
    ownerId: "own-1",
    startDate: "2026-09-05",
    endDate: "2026-09-09",
    pickupLocation: "Kigali — Kicukiro",
    returnLocation: "Kigali — Kicukiro",
    extras: [],
    totalPrice: 300000,
    bookingFee: 0,
    status: "picked_up",
    paymentMethod: "card",
    paymentPoint: "pickup",
    paymentConfirmed: true,
    qrCode: "LRA-BK1004-GRACE",
    driverName: "Grace Umutoni",
    driverLicense: "DL-2021-90214",
    createdAt: "2026-09-01T16:45:00Z",
  },
  {
    id: "bk-1005",
    customerId: "cus-2",
    vehicleId: "veh-8",
    ownerId: "own-5",
    startDate: "2026-07-20",
    endDate: "2026-07-24",
    pickupLocation: "Kigali — Kicukiro",
    returnLocation: "Kigali — Kicukiro",
    extras: ["child-seat"],
    totalPrice: 340000,
    bookingFee: 0,
    status: "completed",
    paymentMethod: "momo",
    paymentPoint: "office",
    paymentConfirmed: true,
    qrCode: "LRA-BK1005-SAMUEL",
    driverName: "Samuel Nkurunziza",
    driverLicense: "DL-2019-55231",
    createdAt: "2026-07-15T11:20:00Z",
  },
];

const reviewBase = {
  photos: [] as string[],
  tags: [] as string[],
  status: "published" as const,
  flagCount: 0,
  editCount: 0,
  isVerifiedBooking: true,
  helpfulCount: 0,
};

export const REVIEWS: Review[] = [
  {
    ...reviewBase,
    id: "rev-1",
    bookingId: "bk-1002",
    vehicleId: "veh-5",
    customerId: "cus-1",
    ownerId: "own-2",
    customerName: "Diane Ingabire",
    rating: 5,
    title: "Seamless airport pickup",
    comment:
      "Seamless airport pickup — the Corolla was spotless and the owner was waiting when I landed. Paid cash on arrival, zero hassle.",
    tags: ["Clean car", "Punctual", "Smooth pickup"],
    helpfulCount: 12,
    reply: {
      id: "rpl-1",
      reviewId: "rev-1",
      ownerId: "own-2",
      ownerName: "Aline Uwase",
      comment: "Thank you Diane! Always a pleasure hosting you.",
      createdAt: "2026-08-16T08:00:00Z",
    },
    createdAt: "2026-08-15T09:00:00Z",
    updatedAt: "2026-08-15T09:00:00Z",
  },
  {
    ...reviewBase,
    id: "rev-2",
    bookingId: "bk-1005",
    vehicleId: "veh-8",
    customerId: "cus-2",
    ownerId: "own-5",
    customerName: "Samuel Nkurunziza",
    rating: 5,
    comment:
      "Took the Sorento to Akagera with the family. Child seat was already installed. Excellent service.",
    tags: ["Great service"],
    helpfulCount: 6,
    createdAt: "2026-07-25T12:30:00Z",
    updatedAt: "2026-07-25T12:30:00Z",
  },
  {
    ...reviewBase,
    id: "rev-3",
    bookingId: "bk-x1",
    vehicleId: "veh-1",
    customerId: "cus-3",
    ownerId: "own-1",
    customerName: "Grace Umutoni",
    rating: 5,
    comment:
      "The Land Cruiser handled Volcanoes NP roads like a dream. Worth every franc.",
    tags: ["As described", "Would rent again"],
    helpfulCount: 9,
    createdAt: "2026-06-18T15:00:00Z",
    updatedAt: "2026-06-18T15:00:00Z",
  },
  {
    ...reviewBase,
    id: "rev-4",
    bookingId: "bk-x2",
    vehicleId: "veh-3",
    customerId: "cus-2",
    ownerId: "own-1",
    customerName: "Samuel Nkurunziza",
    rating: 4,
    comment: "Great hybrid economy — did Kigali to Huye on half a tank.",
    tags: ["Good value"],
    helpfulCount: 3,
    createdAt: "2026-05-30T10:00:00Z",
    updatedAt: "2026-05-30T10:00:00Z",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t-1",
    name: "Diane Ingabire",
    location: "Kigali",
    quote:
      "Booked a car in under a minute and paid at pickup. LORA is the only rental service I trust in Kigali.",
    rating: 5,
  },
  {
    id: "t-2",
    name: "Samuel Nkurunziza",
    location: "Musanze",
    quote:
      "The 4x4 was ready for the volcano trails and the owner even shared route tips. Premium experience.",
    rating: 5,
  },
  {
    id: "t-3",
    name: "Aline Uwase",
    location: "Kigali",
    quote:
      "As a car owner, LORA handles everything — bookings, verification, payouts. My fleet earns while I sleep.",
    rating: 5,
  },
];

// ─── Blog seed posts ─────────────────────────────────────────────────────────
export const POSTS: Post[] = [
  {
    id: "post-1",
    slug: "top-10-drives-rwanda",
    title: "Top 10 Scenic Drives in Rwanda",
    excerpt: "From the misty switchbacks of the Congo-Nile Trail to the savanna roads of Akagera — the routes every driver should experience.",
    content: `Rwanda packs an astonishing amount of scenery into a small country. Here are the ten drives we recommend to every LORA customer.\n\n## 1. Kigali → Musanze (Volcanoes)\nThe classic. Two hours of terraced hills climbing toward the Virunga volcanoes. Take the early morning departure to catch the mist lifting off the peaks.\n\n## 2. The Congo-Nile Trail (Rubavu → Rusizi)\n227 km along Lake Kivu's shoreline — coffee plantations, fishing villages, and some of the best sunset views in East Africa. A 4x4 is strongly recommended.\n\n## 3. Kigali → Akagera National Park\nEast through Rwamagana to the savanna. Giraffes, zebras and elephants within two hours of the capital.\n\n## 4. Huye → Nyungwe Forest\nTea estates give way to ancient rainforest. Stop at the canopy walkway.\n\n## 5. Musanze → Rubavu via the Twin Lakes\nBurera and Ruhondo shimmer between the volcanoes — arguably the most photogenic hour of driving in the country.\n\n## 6–10. Honourable mentions\nKigali → Nyanza (King's Palace), the Bugesera lakes loop, Nyagatare's eastern plains, Karongi's island-dotted bays, and the Kigali ring road at golden hour.\n\n**Rent the right car:** a 4x4 for the north and west, a comfortable sedan for Kigali–Huye. All LORA vehicles are insured and inspected.`,
    coverImage: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?f_auto&q_auto&w_1600",
    category: "travel",
    tags: ["road trips", "itinerary", "4x4"],
    publishedAt: "2025-06-10T08:00:00Z",
    createdAt: "2025-06-10T08:00:00Z",
  },
  {
    id: "post-2",
    slug: "kigali-to-musanze-road-trip",
    title: "Kigali to Musanze: The Ultimate Road Trip Guide",
    excerpt: "Everything you need for the 90-minute drive to gorilla country — fuel stops, viewpoints, and where to eat in Musanze.",
    content: `The Kigali–Musanze highway is Rwanda's most travelled tourist route, and for good reason.\n\n## The route\nLeave Kigali via the northern bypass, join the RN4 through Base and Rulindo, then climb into the Virunga foothills. Total distance: ~95 km, about 90 minutes without stops.\n\n## Worth stopping for\n- **Nyirangarama** — the famous roadside market for roasted maize and passion fruit\n- **Rulindo viewpoints** — terraced hillsides that look hand-drawn\n- **Kinigi** — the gorilla trekking briefing point, 15 min past Musanze town\n\n## Driving tips\nSpeed cameras are active the whole way — stick to 60 km/h in towns, 80 on the open road. Fuel up in Kigali; Musanze prices run slightly higher.\n\n## The car\nA sedan handles the paved highway fine, but if you're continuing to the Twin Lakes or park tracks, take a 4x4. LORA's airport-approved fleet can meet you at KGL with the car ready.`,
    coverImage: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?f_auto&q_auto&w_1600",
    category: "destinations",
    tags: ["musanze", "gorillas", "guide"],
    publishedAt: "2025-07-02T08:00:00Z",
    createdAt: "2025-07-02T08:00:00Z",
  },
  {
    id: "post-3",
    slug: "why-rent-4x4-rwanda",
    title: "Why You Should Rent a 4x4 in Rwanda",
    excerpt: "Rwanda's beauty lives off the tarmac. Here's when a 4x4 is essential — and when a sedan will do.",
    content: `The land of a thousand hills rewards drivers who go beyond the main roads.\n\n## When you need a 4x4\n- **Akagera game tracks** — mandatory in the park\n- **Congo-Nile Trail** — unpaved sections, especially in the rains\n- **Volcanoes trailheads** — the last kilometres to Bisoke or Muhabura are rough\n- **Nyungwe's back roads** — steep, muddy, spectacular\n\n## When a sedan is fine\nKigali–Huye, Kigali–Rubavu via the main highway, and all city driving. Rwanda's primary roads are excellent.\n\n## The math\nA 4x4 costs roughly 40% more per day — but one muddy hillside rescue costs far more. If your itinerary touches a national park, book the Land Cruiser.\n\nAll LORA 4x4s are inspected, insured, and come with 24/7 roadside support.`,
    coverImage: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?f_auto&q_auto&w_1600",
    category: "tips",
    tags: ["4x4", "advice", "safari"],
    publishedAt: "2025-08-15T08:00:00Z",
    createdAt: "2025-08-15T08:00:00Z",
  },
];

// ─── Lookup helpers ──────────────────────────────────────────────────────────
export const vehicleById = (id: string) => VEHICLES.find((v) => v.id === id);
export const userById = (id: string) => ALL_USERS.find((u) => u.id === id);
export const ownerOf = (vehicle: Vehicle) => userById(vehicle.ownerId);
export const reviewsFor = (vehicleId: string) =>
  REVIEWS.filter((r) => r.vehicleId === vehicleId);
